### ISSUE TITLE
"use"ing modules from other directories is painful

### ISSUE THREAD

**Issue by dvd0bvb** [TheGreatUsername/Hairy-Pigeon#20]
consider the module test.hp, the contents of which are 

```
use "CompilerDirectory/buffer.hp"

...
```

compiling with `pigeon test.hp -O` throws an error

```
Traceback (most recent call last):
  File "/home/david/hairypigeon/main.py", line 21, in copyanything
    shutil.copytree(src, dst)
  File "/usr/lib/python3.10/shutil.py", line 556, in copytree
    with os.scandir(src) as itr:
NotADirectoryError: [Errno 20] Not a directory: '/home/david/Repos/Hairy-Pigeon/Hairy Pigeon (Linux and Mac version)/CompilerParts/buffer.hp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/david/hairypigeon/main.py", line 94, in <module>
    copyuses(tocomp)
  File "/home/david/hairypigeon/main.py", line 91, in copyuses
    copy(originaldir, f'{scriptdir}/CompileDirectory', fname)
  File "/home/david/hairypigeon/main.py", line 29, in copy
    copyanything(src + '/' + name, dst + '/' + name)
  File "/home/david/hairypigeon/main.py", line 24, in copyanything
    shutil.copy(src, dst)
  File "/usr/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 256, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/david/hairypigeon/CompileDirectory/CompilerParts/buffer.hp'
```

**Comment by TheGreatUsername** [comment]
Use needs some serious upgrades and currently is just a literal path to a file to "#include". Where is test.hp? If it's in the same folder as CompilerDirectory you might need to use `use "./CompilerDirectory/buffer.hp"`

**Comment by dvd0bvb** [comment]
test.hp was in `home/david/Repos/Hairy-Pigeon/Hairy Pigeon (Linux and Mac version)/CompilerParts` 
I did try `./CompilerDirectory/buffer.hp` and got the same error
